---
depoyment:
  tasks:
    - export DEPLOYPATH=/home/courier-assistant/
    - /bin.cp -r * $DEPLOYPATH
    - composer install
    - npm install
    - npm run build
    - php artisan migrate
    - php artisan cache:clear
    - php artisan config:clear